FROM node:14-alpine

WORKDIR /app

ENTRYPOINT [ "npm" ]


# docker build -t mynpm .
# docker run -it -v /Users/johncevallos/Documents/joancema/classes/novenoAB20231/2utilityContainer/otros:/app mynpm init
# docker run -it -v /Users/johncevallos/Documents/joancema/classes/novenoAB20231/2utilityContainer/otros:/app mynpm install express --save
# docker run -it -v /Users/johncevallos/Documents/joancema/classes/novenoAB20231/2utilityContainer/otros:/app mynpm install